#!/bin/sh

set -e

echo cwd: $(pwd)
mkdir -p ./_themes/leap-day-2
ls -al
rm -rf ./_themes/leap-day-2
ln -s . ./_themes/leap-day-2
# cp -r _includes _layouts _sass assets LICENSE README.md  ./_themes/leap-day-2/
ls -al ./_themes/
ls -al ./_themes/leap-day-2/./
gem "leap-day-2", path: "./_themes/leap-day-2"
bundle install
