on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - name: Setup encoding and terminal codepage
        run: |
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: chmod link local theme
        run: |
          pwd
          ls -la
          chmod +x script/link-local-theme
      - name: link local theme
        run: script/link-local-theme
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
